parameters:
  name: pool
  type: string

stages:
- stage: version
  displayName: set version
  variables:
  - name: source
    value: $[variables['resources.pipeline.ci.sourceBranch']]
  - name: version
    value: $[replace(variables.source, 'refs/heads/release/', '' )]
  - name: infraVersion
    value: $[counter(variables.version, 0)]
  jobs:
  - job: set_build_number
    displayName: Set build number
    pool: ${{ parameters.pool }}
    steps:
    - script: echo "##vso[build.updatebuildnumber]$(version)-$(infraVersion)"
    - bash:  echo "##vso[task.setvariable variable=tagVersion;isOutput=true]$(version)-$(infraVersion)"
      name: VersionStageTag
    - bash: echo '$(version)-$(infraVersion)'
  - job: commit_version
    displayName: Commit Version
    dependsOn: set_build_number
    pool: ${{ parameters.pool }}
    variables:
      PYTHONUSERBASE: $(Pipeline.Workspace)
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
    - script: |
        git fetch origin main
        git checkout origin/main
      displayName: git fetch
    - script: |
        python -m pip install yaml-patch
        $(PYTHONUSERBASE)/bin/yaml-patch -f defaults/product.yaml image.tag='$(version)' > tmp.yaml && mv tmp.yaml defaults/product.yaml
        $(PYTHONUSERBASE)/bin/yaml-patch -f defaults/product.yaml image.infra='$(infraVersion)' > tmp.yaml && mv tmp.yaml defaults/product.yaml
        cat defaults/product.yaml
      target: python
      displayName: tag patch
    - script: |
        git config user.email "email"
        git config user.name "Ubuntu"
        git add .
        git commit -m "Bump version" -m "skip-checks: true"
        git push origin HEAD:main

        git tag -am '$(version)-$(infraVersion)' '$(version)-$(infraVersion)'
        git push --force --tags
      displayName: git commit
  condition: and(or(in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'ResourceTrigger'), and(in(variables['Build.Reason'], 'Manual'), startsWith(variables['Build.SourceBranch'], 'refs/heads/main'))), ne(variables['resources.pipeline.ci.sourceBranch'], 'refs/heads/main'))